# Generated by Django 2.1.2 on 2019-01-01 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181226_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliablity',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, null=None),
            preserve_default=False,
        ),
    ]
