# Generated by Django 2.1.2 on 2019-06-28 04:14

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190107_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliablity',
            name='not_available',
            field=models.DateField(default=None, help_text='You can only select one date per submit.', validators=[accounts.validators.validate_time_request]),
        ),
    ]
