# Generated by Django 2.1.2 on 2019-06-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190628_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliablity',
            name='not_available',
            field=models.DateField(default=None, help_text='You can only select one date per submit.'),
        ),
    ]
