# Generated by Django 2.1.2 on 2018-11-02 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20181029_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Product'),
        ),
    ]
