# Generated by Django 2.1.2 on 2018-11-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_foodorder_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prep_amount',
            new_name='order_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.DeleteModel(
            name='FoodOrder',
        ),
    ]
