# Generated by Django 2.1.2 on 2018-11-09 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_remove_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_amount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='items.Order'),
            preserve_default=False,
        ),
    ]
