# Generated by Django 2.1.2 on 2018-11-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_product_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='order_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='par_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
