# Generated by Django 2.1.2 on 2018-12-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PrepWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank='False', help_text='Add one item at a time. ', max_length=200)),
                ('description', models.TextField(blank='False', help_text='Add instructions to remove any confusion. ', max_length=200)),
                ('day_of_week', models.CharField(blank='False', choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Please set the day of week. ', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='day_of_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.PrepWork'),
        ),
    ]
