# Generated by Django 2.1.2 on 2018-11-12 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thur', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=15)),
                ('amount_needed', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='prepwork',
            name='description',
            field=models.TextField(help_text='Only use if needed, to help remove any confusion. ', max_length=200),
        ),
        migrations.AddField(
            model_name='day',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.PrepWork'),
        ),
        migrations.AddField(
            model_name='prepwork',
            name='day_of_week',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='todo.Day'),
            preserve_default=False,
        ),
    ]
