# Generated by Django 2.1.2 on 2019-01-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepwork',
            name='item',
            field=models.CharField(blank='False', max_length=200),
        ),
    ]
