# Generated by Django 2.1.2 on 2018-11-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20181112_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_of_week',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thur', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], help_text='Please set the day of week. ', max_length=20),
        ),
        migrations.AlterField(
            model_name='prepwork',
            name='description',
            field=models.TextField(help_text='add instructions to remove any confusion. ', max_length=200),
        ),
    ]
