# Generated by Django 2.1.2 on 2018-11-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20181112_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepwork',
            name='day_of_week',
            field=models.CharField(blank='True', choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thur', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], help_text='Please set the day of week. ', max_length=20),
        ),
        migrations.AlterField(
            model_name='prepwork',
            name='description',
            field=models.TextField(help_text='Add instructions to remove any confusion. ', max_length=200),
        ),
        migrations.AlterField(
            model_name='prepwork',
            name='item',
            field=models.CharField(help_text='Add one item at a time. ', max_length=200),
        ),
    ]
