# Generated by Django 2.1.2 on 2018-11-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20181113_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepwork',
            name='description',
            field=models.TextField(blank='True', help_text='Add instructions to remove any confusion. ', max_length=200),
        ),
        migrations.AlterField(
            model_name='prepwork',
            name='item',
            field=models.CharField(blank='True', help_text='Add one item at a time. ', max_length=200),
        ),
    ]
